[package]
name = "nano-rag"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
colored_text = "0.3.0"
ordered-float = "5.1.0"
rand = "0.9.2"
rayon = "1.11.0"
rkyv = "0.8.14"
serde = { version = "1.0.228", features = ["derive"] }
